### ISSUE TITLE
Do not declare code-review as a dependency while keeping its functionality

### ISSUE THREAD

**Issue by Andre0991** [elken/embark-vc#4]
Hi. `embark-vc` declares `code-review` as a dependency. I don't use that package.

Is there any way of installing `embark-vc` without getting `code-review`?

Additionally, I wonder if it's possible to resolve `code-review` dynamically and only offer its related functions when it's present, thus not needing to declare it as a dependency at all.

**Comment by elken** [comment]
Thanks for the interest! Try the `feat/code-review-optional` branch and let me know :)

**Comment by Andre0991** [comment]
Thanks, it works.

**Comment by Andre0991** [comment]
A related suggestion: is the `s` dependency used only for `s-replace`? If so, I wonder if it could be replaced (no pun intended) with `string-replace`. Note that this function was introduced by Emacs 28, though. If you want to enable older versions to still use `embark-vc`, I think requiring `compat-28` would help: https://git.sr.ht/~pkal/compat/tree/master/item/compat-28.el

Of course, that would simply swap dependencies. But using `compat` and a core function is nicer than requiring `s.el`, IMO.
