### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Andre0991** [elken/embark-vc#6]
Hi!

I have some minor suggestions for `embark-vc`:

### s dependency

A related suggestion: is the `s` dependency used only for `s-replace`? If so, I wonder if it could be replaced (no pun intended) with `string-replace`. Note that this function was introduced by Emacs 28, though. If you want to enable older versions to still use `embark-vc`, I think requiring `compat-28` would help: https://git.sr.ht/~pkal/compat/tree/master/item/compat-28.el

Of course, that would simply swap dependencies. But using `compat` and a core function is nicer than requiring `s.el`, IMO.

### the embark-vc name

As you might know, `vc` has a very specific meaning in Emacs: the version control built-in package.
Given that, given `embark-vc` name, I would expect this package to deal with the Emacs `vc` stuff, but that's not the case (`embark` already does that).
So I suggest renaming the package, as it's misleading.

Note also that Emacs packages should start with a unique prefix to avoid collisions.
This package adopts `embark-vc`, which is arguably not enough for avoiding conflicts with `embark`, which could have a function starting with `embark-vc`.

### `B` binding
`embark-vc` uses `B` for `forge-browse-pullreq`, but `B` is mapped as default to `embark-become`.
While I think I will never use `embark-become` in an `embark-vc` context, I think having the same binding is strange, since I'm used to `B` as become and `embark` offers its own actions as upper case letters.

Thanks!

**Comment by elken** [comment]
> s dependency

You're right that you're just swapping one dependency for another, so I don't see the point.

> the embark-vc name

It does have a specific meaning within emacs and I will indeed add support for vc-mode eventually but it's also widely accepted (and clarified within the docs) that vc is short for version control :D 

> `B` binding

I suppose I could make `c` checkout and `b` browse then
